# Brief Introduction to PyTorch

---



In this notebook, we will introduce some basical usage of PyTorch. You can get familiar with PyTorch by reading from start. In the end you have to complete some codes and submit them.

## Environment
To running this code, you have to prepare a python environment. We recommend python version >= 3.8. You will need to install `torch`, `numpy` and `jupyter` packages. And in order to run the tests locally, you also need to install `scikit-learn` and `matplotlib`.

In [ ]:
import torch
import numpy as np

## Data Type (Tensor)
The math operations in PyTorch is based on Tensors, just like most of the operations in numpy is based on numpy arrays. In practical usage, tensors are similar to arrays in numpy, which can represent matrics of high dimensions. For example, a tensor can be used to represent not only a one-bit array, but also a two-dimensional matrix and an image with rgb3 channels.

### Tensor Creation

There are a few ways to create tensors in PyTorch, the easiest way is to create from a Python List.

In [ ]:
a = torch.tensor([[1,2,3], [4,5,6]])
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])


We can also create a tensor from a numpy array.

In [ ]:
b_array = np.array([[6,5,4], [3,2,1]])
b = torch.from_numpy(b_array)
print(b)

tensor([[6, 5, 4],
        [3, 2, 1]])


Similar to numpy, we can create some special values directly.

In [ ]:
rand_v = torch.rand(size=(2, 3), dtype=torch.float32)
ones_v = torch.ones(size=(2, 3), dtype=torch.float32)
zeros_v = torch.zeros(size=(2,3), dtype=torch.float32)
diag_v = torch.eye(3, dtype=torch.float32)

print(rand_v)
print(ones_v)
print(zeros_v)
print(diag_v)

tensor([[0.1550, 0.2200, 0.9260],
        [0.3989, 0.6363, 0.6292]])
tensor([[1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### Tensor Operation

We can index tensors in a similar way to numpy.

In [ ]:
a = torch.tensor([[1,2,3], [4,5,6]])

print(a)

print(a[:, 2])

print(a[1, 2])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([3, 6])
tensor(6)


Tensors also support many arithmetic operations similar to numpy.

In [ ]:
# Create a 2x3 tensor
a = torch.tensor([[1,2,3], [4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Elementwise addition and multiplication with a constant number
a = a + 2
print(a)

a = a * 3
print(a)

tensor([[3, 4, 5],
        [6, 7, 8]])
tensor([[ 9, 12, 15],
        [18, 21, 24]])


In [ ]:
# Elementwise multiplication between two tensors
a = torch.ones(size=(3, 3)) * 2
b = torch.ones(size=(3, 3)) * 3
c = a * b
print(c)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [ ]:
# Matrix multiplication
a = torch.tensor([[1, 2], [3, 4]])
print(a)
b = torch.tensor([[5, 6], [7, 8]])
print(b)
c = torch.matmul(a, b)
print(c)

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
# Matrix multiply vector
a = torch.tensor([[1, 2], [3, 4]])
print(a)
v = torch.tensor([6, 7])
print(v)
c = torch.matmul(a, v)
print(c)

tensor([[1, 2],
        [3, 4]])
tensor([6, 7])
tensor([20, 46])


## Matrix Operation
In PyTorch, 2D tensors can be viewed as matrices. And torch supports some common operations on matrices.

### Inverse Matrix and Pseudoinverse Matrix
Pytorch supports operations to find the inverse and pseudoinverse of a matrix.

In [ ]:
# inverse of a matrix
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
a_inv = torch.linalg.inv(a)
print("A x A':")
print(torch.matmul(a, a_inv))

# pseudoinverse of a matrix
b = torch.rand(size=(2, 2), dtype=torch.float32)
b_pinv = torch.linalg.pinv(b)
print("B x pinv(B)")
print(torch.matmul(b, b_pinv))

A x A':
tensor([[1., 0.],
        [0., 1.]])
B x pinv(B)
tensor([[ 1.0000e+00,  1.1921e-07],
        [-1.1921e-07,  1.0000e+00]])


### Transpose of a matrix
Pytorch supports transpose operation for 2D tensor

In [ ]:
# transpose of a matrix
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(a)
a_T = torch.t(a)
print(a_T)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 3.],
        [2., 4.]])


### Concatenate matrices
You can concatenate multiple matrices using PyTorch.

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
c = torch.cat((a, b), dim=1)
print(c)
d = torch.cat((a, b), dim=0)
print(d)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


### PyTorch Documentation
A good way to learn PyTorch operations is to look up the documentation (https://pytorch.org/docs/stable/index.html). Some of the tasks in the following involve simple PyTorch operations that you can find in the documentation.

## Task 1 (2 points)
Complete a function that returns a diagonal matrix of dtype torch.float32, and the values on the diagonal are all the same as the input value x.

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def diag_matrix(n, x):
    '''
    Inputs:
    n: number of rows and columns
    x: the diagnal value
    Output:
    D: 2D tensor of shape (n, n)
    '''
    # complete this function, return a tensor with the shape n x n, and the values on the diagonal are all x, all other values are zero
    return x * torch.eye(n,dtype=torch.float32)
diag_matrix(3,3)

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

## Task 2 (2 points)
Complete a function that returns the mean square loss (MSE) of two given 1D tensors. Note that the MSE loss $L_{\text{MSE}}=\dfrac{1}{n}\Vert y_{\text{true}}-y_{\text{pred}}\Vert_2^2$, $y_{\text{true}}, y_{\text{pred}}\in\mathbb{R}^n$

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def mean_square_loss(y_true, y_pred):
    '''
    Inputs:
    y_true: 1D tensor of shape (n)
    y_pred: 1D tensor of shape (n)
    Output:
    loss: tensor containing the mean square loss of y_true and y_pred
    '''
    # complete this function, return a tensor with one float, the mean square loss of y_true and y_pred.
    loss = torch.nn.MSELoss()
    return loss(y_true,y_pred)
mean_square_loss(torch.Tensor([1.0,2.0,3.0]),torch.Tensor([1.8,2.4,2.8]))

tensor(0.2800)

## Task 3 (2 points)
Complete a function that extracts all even-indexed rows of a given 2D tensor.

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def extract_even_rows(matrix):
    '''
    Inputs:
    matrix: 2D tensor of shape (n, m)
    Output:
    matrix_even: 2D tensor of all even-indexed rows of matrix, e.g. 0, 2, 4...
    '''
    # return a tensor containing all even-indexed rows of matrix
    return matrix[::2]
extract_even_rows(torch.rand(3,3))

tensor([[0.9703, 0.8962, 0.6179],
        [0.3915, 0.9240, 0.2542]])

## Task 4 (2 points)
Complete a function that takes a 2D tensor and returns a new 1D tensor consisting of the elements in the specified column of the original tensor that are greater than a specified value threshold.

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def filter_column(tensor, column_idx, threshold):
    """
    Returns elements from the column with index column_idx of the tensor that are greater than the threshold.
    """
    # Implement this function
    column = tensor[:,column_idx] #This reminds me of pandas slicing and indexing
    elements = column[column > threshold]
    return elements
filter_column(torch.rand(3,3),1,0.13)

tensor([0.8765, 0.7728, 0.4371])

## Task 5 (1 points)
Given an input tensor, returns a tensor with all dimensions of size 1 removed. (Hint: PyTorch has a function for this operation, look up the documentation.)

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def remove_dim(tensor):
    """
    Returns a tensor with all specified dimensions of input tensor of size 1 removed.
    """
    # Implement this function
    print(tensor.size())
    return torch.squeeze(tensor)
remove_dim(torch.zeros(2,1,2,1,2))

torch.Size([2, 1, 2, 1, 2])


tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

## Task 6 (1 points)
Complete a function that clamps all values of a given tensor into a specified range [min_val, max_val]. (Hint: PyTorch has a function for this operation, look up the documentation.)

In [ ]:
#export
import torch
### DO NOT CHANGE ANY CODE ABOVE THIS LINE IN THIS CELL ###
def clamp_tensor(tensor, min_val, max_val):
    """
    Clamps the tensor values to the range [min_val, max_val].
    """
    # Implement this function
    print(tensor)
    return torch.clamp(tensor,min_val,max_val)
clamp_tensor(torch.rand(3,3),0.5,0.9)

tensor([[0.2971, 0.0233, 0.9067],
        [0.5813, 0.0475, 0.0564],
        [0.5598, 0.8851, 0.3897]])


tensor([[0.5000, 0.5000, 0.9000],
        [0.5813, 0.5000, 0.5000],
        [0.5598, 0.8851, 0.5000]])

## Submission
Ensure you've thoroughly tested your code locally before submitting it for evaluation. Your submission to Gradescope should be this .ipynb file named `hw1_torch_intro.ipynb`.

### Submission Checklist:

Ensure your submission contains the following items:

1. `hw1_torch_intro.ipynb`: The torch jupyter notebook containing all your code and answers.

### Submission Instructions:

- **File Format**: Submit this file `hw1_torch_intro.ipynb`.
- **Validation**: Before submitting, verify your code runs as expected and all outputs align with anticipated results.